### ISSUE TITLE
Problem with Contributing Guideline set up

### ISSUE THREAD

**Issue by aliciakozlowski** [src-d/landing#290]
- Versions:
  - Go: `go version go1.11.1 darwin/amd64`
  - Yarn: `1.10.1`
- I was going through the [development part of Contributing Guidelines](https://github.com/src-d/landing/blob/master/CONTRIBUTING.md#development) to run the server locally so I could make a make some changes to the project for a PR, and kept running into an error.
- All of the previous requirements listed in the guidelines are installed but running the `make serve` command shows an error:

```bash
alicia~» go version                                                 [18:39:01]
go version go1.11.1 darwin/amd64
alicia~» go env GOPATH;                                             [18:39:16]
/Users/aliciakozlowski/go
alicia~» go get github.com/src-d/landing/...                        [18:39:23]
alicia~» cd $GOPATH/src/github.com/src-d/landing                    [18:39:43]
aliciagithub.com/src-d/landing(master)» yarn --version;             [18:40:05]
1.10.1
aliciagithub.com/src-d/landing(master)» make build                  [18:41:03]
git clone --quiet --depth 1 https://github.com/src-d/ci.git /Users/aliciakozlowski/go/src/github.com/src-d/landing/.ci;
Downloading https://github.com/spf13/hugo/releases/download/v0.21/hugo_0.21_macOS-64bit.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   151    0   151    0     0    308      0 --:--:-- --:--:-- --:--:--   308
100   618    0   618    0     0    900      0 --:--:-- --:--:-- --:--:--  603k
100 4435k  100 4435k    0     0  1901k      0  0:00:02  0:00:02 --:--:-- 5716k
/Users/aliciakozlowski/go/src/github.com/src-d/landing/.hugo/hugo --config=hugo.config.yaml --destination=public --baseURL=//sourced.tech
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
8 regular pages created
8 other pages created
0 non-page files copied
0 paginator pages created
1 classes created
0 categories created
total in 14 ms
aliciagithub.com/src-d/landing(master)» LANDING_URL=//localhost PORT=8081 make serve
rm -rf /Users/aliciakozlowski/go/src/github.com/src-d/landing/.hugo
Downloading https://github.com/spf13/hugo/releases/download/v0.21/hugo_0.21_macOS-64bit.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   151    0   151    0     0    296      0 --:--:-- --:--:-- --:--:--   296
100   618    0   618    0     0    899      0 --:--:-- --:--:-- --:--:--   899
100 4435k  100 4435k    0     0  1996k      0  0:00:02  0:00:02 --:--:-- 4281k
yarn run serve
yarn run v1.10.1
$ concurrently --kill-others "yarn run webpack-watcher" "make hugo-server" "yarn run api-run"
/bin/sh: concurrently: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [serve] Error 1
aliciagithub.com/src-d/landing(master)» yarn start                                         [18:50:15]
yarn run v1.10.1
$ node_modules/.bin/termax server
/bin/sh: node_modules/.bin/termax: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
aliciagithub.com/src-d/landing(master)» make serve                                         [18:51:12]
rm -rf /Users/aliciakozlowski/go/src/github.com/src-d/landing/.hugo
Downloading https://github.com/spf13/hugo/releases/download/v0.21/hugo_0.21_macOS-64bit.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   151    0   151    0     0    250      0 --:--:-- --:--:-- --:--:--   250
100   618    0   618    0     0    789      0 --:--:-- --:--:-- --:--:--  603k
100 4435k  100 4435k    0     0  1700k      0  0:00:02  0:00:02 --:--:-- 5310k
yarn run serve
yarn run v1.10.1
$ concurrently --kill-others "yarn run webpack-watcher" "make hugo-server" "yarn run api-run"
/bin/sh: concurrently: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [serve] Error 1
aliciagithub.com/src-d/landing(master)» yarn install concurrently                          [18:51:25]
yarn install v1.10.1
error `install` has been replaced with `add` to add new dependencies. Run "yarn add concurrently" instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
aliciagithub.com/src-d/landing(master)» yarn add concurrently                              [18:54:27]
yarn add v1.10.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/2] ⡀ fsevents
warning Error running install script for optional dependency: "/Users/aliciakozlowski/go/src/github.com/src-d/landing/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments: 
Directory: /Users/aliciakozlowski/go/src/github.com/src-d/landing/node_modules/fsevents
Output:

---------- a bunch of things that probably don´t matter -----------

4 warnings and 1 error generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/aliciakozlowski/go/src/github.com/src-d/landing/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/10.11.0/bin/node" "/Users/aliciakozlowski/go/src/github.com/src-d/landing/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/aliciakozlowski/go/src/github.com/src-d/landing/node_modules/node-sass
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1

aliciagithub.com/src-d/landing(master)» make serve                                         [19:01:39]
rm -rf /Users/aliciakozlowski/go/src/github.com/src-d/landing/.hugo
Downloading https://github.com/spf13/hugo/releases/download/v0.21/hugo_0.21_macOS-64bit.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   151    0   151    0     0    287      0 --:--:-- --:--:-- --:--:--   287
100   618    0   618    0     0    873      0 --:--:-- --:--:-- --:--:--   873
100 4435k  100 4435k    0     0  1119k      0  0:00:03  0:00:03 --:--:-- 1622k
yarn run serve
yarn run v1.10.1
$ concurrently --kill-others "yarn run webpack-watcher" "make hugo-server" "yarn run api-run"
$ go run api/api.go
$ webpack --config=webpack.config.js --watch --debug --verbose --progress --colors
[0]  10% building modules 1/1 modules 0 active                                         
[0] Webpack is watching the files...
[0] 
 11% building modules 16/19 modules 3 active ...dules/lightbox2/dist/css/lightbox.css/Users/aliciakozlowski/go/src/github.com/src-d/landing/.hugo/hugo server --config=hugo.config.yaml --destination=public --port=80 --baseURL=//sourced.tech --watch --buildDrafts
[1] Error: Server startup failed: listen tcp 127.0.0.1:80: bind: permission denied
[1] make[1]: *** [hugo-server] Error 255
[1] make hugo-server exited with code 2
--> Sending SIGTERM to other processes..
[2] [GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
[2] 
[2] [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
[2]  - using env:	export GIN_MODE=release
[2]  - using code:	gin.SetMode(gin.ReleaseMode)
[2] 
[2] [GIN-debug] GET    /                         --> github.com/src-d/landing/api/handlers.Head.func1 (4 handlers)
[2] [GIN-debug] GET    /api/posts/:kind          --> github.com/erizocosmico/gin-cache.CachePage.func1 (4 handlers)
[2] [GIN-debug] GET    /api/positions            --> github.com/erizocosmico/gin-cache.CachePage.func1 (4 handlers)
[2] [GIN-debug] POST   /api/invite               --> github.com/src-d/landing/api/handlers.SlackInvite.func1 (4 handlers)
[2] [GIN-debug] Listening and serving HTTP on :8080
[0] yarn run webpack-watcher exited with code 1
--> Sending SIGTERM to other processes..
[2] yarn run api-run exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [serve] Error 1
```

**Comment by carlosms** [comment]
It looks like we have a bug and make does not install the frontend dependencies.

Please try:
```bash
make js-dependencies
make serve
```

**Comment by aliciakozlowski** [comment]
Tried to run through it again, still running into trouble...

```
alicia➜~» go get github.com/src-d/landing/...                                                                            [11:53:20]
alicia➜~» cd $GOPATH/src/github.com/src-d/landing                                                                        [11:53:36]
alicia➜github.com/src-d/landing(master)» make build                                                                      [11:53:59]
/Users/aliciakozlowski/go/src/github.com/src-d/landing/.hugo/hugo --config=hugo.config.yaml --destination=public --baseURL=//sourced.tech
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
8 regular pages created
8 other pages created
0 non-page files copied
0 paginator pages created
0 categories created
1 classes created
total in 14 ms
alicia➜github.com/src-d/landing(master)» make js-dependencies                                                            [11:54:17]
yarn install --force
yarn install v1.10.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Rebuilding all packages...
[1/2] ⢀ fsevents
warning Error running install script for optional dependency: "/Users/aliciakozlowski/go/src/github.com/src-d/landing/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments: 
Directory: /Users/aliciakozlowski/go/src/github.com/src-d/landing/node_modules/fsevents
Output:

----------------- a lot of text -------------------

4 warnings and 1 error generated.
make[1]: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/aliciakozlowski/go/src/github.com/src-d/landing/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/10.11.0/bin/node" "/Users/aliciakozlowski/go/src/github.com/src-d/landing/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/aliciakozlowski/go/src/github.com/src-d/landing/node_modules/node-sass
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1

make: *** [js-dependencies] Error 1
alicia➜github.com/src-d/landing(master)» LANDING_URL=//localhost PORT=8081 make js-dependencies                          [11:56:03]
yarn install --force
yarn install v1.10.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Rebuilding all packages...
[1/2] ⢀ fsevents
warning Error running install script for optional dependency: "/Users/aliciakozlowski/go/src/github.com/src-d/landing/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments: 
Directory: /Users/aliciakozlowski/go/src/github.com/src-d/landing/node_modules/fsevents
Output:

----------------- a lot of the same text -------------------

4 warnings and 1 error generated.
make[1]: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/aliciakozlowski/go/src/github.com/src-d/landing/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/10.11.0/bin/node" "/Users/aliciakozlowski/go/src/github.com/src-d/landing/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/aliciakozlowski/go/src/github.com/src-d/landing/node_modules/node-sass
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1

make: *** [js-dependencies] Error 1
alicia➜github.com/src-d/landing(master)» LANDING_URL=//localhost PORT=8081 make serve                                    [12:00:29]
rm -rf /Users/aliciakozlowski/go/src/github.com/src-d/landing/.hugo
Downloading https://github.com/spf13/hugo/releases/download/v0.21/hugo_0.21_macOS-64bit.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   151    0   151    0     0    291      0 --:--:-- --:--:-- --:--:--   290
100   618    0   618    0     0    862      0 --:--:-- --:--:-- --:--:--   862
100 4435k  100 4435k    0     0  1816k      0  0:00:02  0:00:02 --:--:-- 3727k
yarn run serve
yarn run v1.10.1
$ concurrently --kill-others "yarn run webpack-watcher" "make hugo-server" "yarn run api-run"

$ webpack --config=webpack.config.js --watch --debug --verbose --progress --colors

[2] 
[2] $ go run api/api.go
[0]   0% compiling

---------------loads 100% ----------------------------

[1] Static file changes detected
[1] 2018-10-11 12:02 +0200
[1] Syncing /js/bundle.js to /Users/aliciakozlowski/go/src/github.com/src-d/landing/public/
[1] Syncing /js/bundle.js.map to /Users/aliciakozlowski/go/src/github.com/src-d/landing/public/
exit
^Cmake: *** [serve] Interrupt: 2

[2] signal: interrupt                                                                                                                        
[1] make[1]: *** [hugo-server] Interrupt: 2
[0] yarn run webpack-watcher exited with code null
--> Sending SIGTERM to other processes..
```

After trying to run the `make serve` again this error came up multiple times:

```
 ERROR in ./~/css-loader?{"modules":false}!./~/postcss-loader/lib?{}!./~/sass-loader/lib/loader.js!./~/lightbox2/dist/css/lightbox.css
[0]     Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (64)
[0]     For more information on which environments are supported please see:
[0]     https://github.com/sass/node-sass/releases/tag/v4.5.3
```

```
ERROR in ./~/lightbox2/dist/css/lightbox.css
[0] Module build failed: ModuleBuildError: Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (64)
[0] For more information on which environments are supported please see:
[0] https://github.com/sass/node-sass/releases/tag/v4.5.3
```

**Comment by smacker** [comment]
I was able to build landing with this changes:
https://github.com/src-d/landing/pull/292

**Comment by ConnorBrereton** [comment]
Ran into issues as well. Note this is pre 
```
make js-dependencies
make serve
```
will post output after trying that fix after first output (see below):
```
connor@Connors-MacBook-Pro:~/go/src/github.com/src-d/landing$ clear

connor@Connors-MacBook-Pro:~/go/src/github.com/src-d/landing$ go version
go version go1.11.1 darwin/amd64
connor@Connors-MacBook-Pro:~/go/src/github.com/src-d/landing$ go env GOPATH
/Users/connor/go
connor@Connors-MacBook-Pro:~/go/src/github.com/src-d/landing$ pwd
/Users/connor/go/src/github.com/src-d/landing
connor@Connors-MacBook-Pro:~/go/src/github.com/src-d/landing$ yarn --version
1.10.1
connor@Connors-MacBook-Pro:~/go/src/github.com/src-d/landing$ make build
/Users/connor/go/src/github.com/src-d/landing/.hugo/hugo --config=hugo.config.yaml --destination=public --baseURL=//sourced.tech
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
8 regular pages created
8 other pages created
0 non-page files copied
0 paginator pages created
1 classes created
0 categories created
total in 17 ms
connor@Connors-MacBook-Pro:~/go/src/github.com/src-d/landing$ LANDING_URL=//localhost PORT=8081 make serve
```
seems that all builds are going along just fine
`Entrypoint main [big] = js/bundle.js css/style.css js/bundle.js.map css/style.css.map`

until here where it hung 
`Syncing /css/style.css to /Users/connor/go/src/github.com/src-d/landing/public/`

```
7 warnings and 1 error generated.
make[1]: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/connor/go/src/github.com/src-d/landing/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command \"/usr/local/Cellar/node/10.12.0/bin/node\" \"/Users/connor/go/src/github.com/src-d/landing/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/connor/go/src/github.com/src-d/landing/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/connor/go/src/github.com/src-d/landing/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64\"
gyp ERR! cwd /Users/connor/go/src/github.com/src-d/landing/node_modules/fsevents
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
```
and the #292 fix is present (see below)
```
connor@Connors-MacBook-Pro:~/go/src/github.com/src-d/landing$ head -15 webpack.config.js 
'use strict';

const path = require('path');
const webpack = require('webpack');
const merge = require('webpack-merge');
const autoprefixer = require('autoprefixer');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

const IS_PRODUCTION = process.env.npm_lifecycle_event === 'build';

const baseConf = {
  entry: [
    path.join(__dirname, 'src/js/index.js')
  ],
  output: {
```

**Comment by smacker** [comment]
hi @ConnorBrereton !

it doesn't "hang", it's listening for changes.
You can try to open http://127.0.0.1:8081/ and see that it works.

**Comment by ConnorBrereton** [comment]
@smacker I did, having figured that the site must be live, and the page rendering on Chrome, Safari, and Firefox hung giving the "refused to connect" message.
