### ISSUE TITLE
Error with node when trying to install package.json

### ISSUE THREAD

**Issue by znegrin** [src-d/landing#344]
I cloned the project but I keep getting an error, apparently related to node:

`/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --scripts-prepend-node-path=auto
module.js:472
    throw err;
    ^

Error: Cannot find module 'isarray'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:10:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

Process finished with exit code 1`

**Comment by dpordomingo** [comment]
@znegrin which command did you run to get that error?

**Comment by znegrin** [comment]
I am using Phpstorm and it suggests me to run "npm install" to install an "aslant" package.
It shows this settings:

![image](https://user-images.githubusercontent.com/14981468/51320447-20bdc100-1a60-11e9-87da-b15a63cc156b.png)

**Comment by dpordomingo** [comment]
Wow ...
No idea.
I wonder if it was because PHP Storm tried some strange configuration for Landing.
In our case, just follow our guide to run the landing from:
https://github.com/src-d/landing/blob/master/CONTRIBUTING.md#development-and-running-the-landing-locally

In your case, I think the second way will suit your necessities better because of the hot reloading feature:
```shell
$ make project-dependencies
$ LANDING_URL=//localhost PORT=8081 yarn start
```

Let me know if it works now.

#### notice

The IDE to be used should not be a problem to run any of our projects, but here, most of us work with [VSCode](https://code.visualstudio.com), available for macOS, Linux, and Windows; and very good integrated with all our projects.
